### ISSUE TITLE
Intercambio de Cartas

### ISSUE THREAD

**Issue by Thargelion** [unlam-tec-movil/A3-2023-H2-Cartas-Super#26]
- [x] Intercambiar cartas mediante QR

**Comment by mavUNLAM** [comment]
[Escaneo qr](https://github.com/unlam-tec-movil/A3-2023-H2-Cartas-Super/pull/51#issue-1995370165)
[Creación qr](https://github.com/unlam-tec-movil/A3-2023-H2-Cartas-Super/pull/47#issue-1993893914)
