### ISSUE TITLE
Mazo de cartas propio

### ISSUE THREAD

**Issue by Thargelion** [unlam-tec-movil/A3-2023-H2-Cartas-Super#27]
- [x] Botón de acceso a las cartas
- [x] Pantalla de visualización de cartas
- [x] ABM de cartas en una tabla local de ROOM

**Comment by mavUNLAM** [comment]
[Mazos personalizados](https://github.com/unlam-tec-movil/A3-2023-H2-Cartas-Super/pull/48#issue-1994192429)
