### ISSUE TITLE
Incorporar cartas al Mazo

### ISSUE THREAD

**Issue by Thargelion** [unlam-tec-movil/A3-2023-H2-Cartas-Super#28]
- [x] Traerme mediante un botón en el Menu del Mazo cartas al azar desde la API
- [x] Guardar esas cartas en la tabla local

**Comment by mavUNLAM** [comment]
[Mazos personalizados](https://github.com/unlam-tec-movil/A3-2023-H2-Cartas-Super/pull/48#issue-1994192429)
