### ISSUE TITLE
Imagen de Perfil del Usuario desde la Cámara

### ISSUE THREAD

**Issue by Thargelion** [unlam-tec-movil/A3-2023-H2-Cartas-Super#32]
- [x] Poder editar la imagen de perfil en base a una captura de la cámara

**Comment by ebaquedano** [comment]
[Imagen de Perfil del Usuario desde la Camara](https://github.com/unlam-tec-movil/A3-2023-H2-Cartas-Super/pull/44#issue-1989214413)
