### ISSUE TITLE
Refactor Componentes

### ISSUE THREAD

**Issue by Thargelion** [unlam-tec-movil/A3-2023-H2-Cartas-Super#36]
- [x] Re estructurar componentes
- [x] Material
- [x] Testing
- [x] System theme

**Comment by mavUNLAM** [comment]
- [Refactor y testing de HeroDuel junto a su viewmodel](https://github.com/unlam-tec-movil/A3-2023-H2-Cartas-Super/pull/43#issue-1988552695)
- [Refactorización de varios composables + testing de composables + soporte parcial para temas claros/obscuros](https://github.com/unlam-tec-movil/A3-2023-H2-Cartas-Super/pull/38#issue-1967253973)
